import type { JournalPost } from './journal-data';

export const POSTS_PART55: JournalPost[] = [
  {
    slug: 'why-do-my-posts-not-show-up-on-unsent-project',
    title: 'Why Do My Posts Not Show Up on Unsent Project',
    excerpt: 'Your posts are not showing up on The Unsent Project and you want answers. Here is why unsent letter platforms silently swallow submissions and how to find one that will not.',
    date: 'June 2026',
    content: `You have submitted to The Unsent Project more than once. Maybe two or three times. Maybe a dozen. Each time, you typed out your message carefully, chose the color that matched the feeling in your chest, pressed submit, and waited. And each time, your post never appeared. It is not in the archive. It is not in the search results. It is as if you never wrote it at all. If this is your experience, you are one of thousands of people asking the same question, and the frustration you are feeling is completely justified.

The experience of submitting something emotionally vulnerable and having it silently disappear is uniquely painful because it mirrors the very dynamic that drove you to the platform in the first place. You had words you could not say to someone. You found a place that promised to hold those words for you. And then that place discarded them without explanation, just as the person you were writing to never heard them. The platform that was supposed to provide an alternative to silence became another form of silence.

There are practical reasons why posts do not show up, and understanding them does not make the experience less frustrating, but it does make it less personal. The most common reason is volume. At its peak, The Unsent Project received an enormous number of submissions daily. No moderation team, whether human, automated, or hybrid, can process that volume without dropping some submissions. Messages get stuck in queues that are never fully cleared. Automated filters flag legitimate posts as potential violations. Database operations time out during peak traffic periods, and the submission that you thought went through was actually lost before it was ever stored.

Another common reason is content filtering false positives. Automated moderation systems use keyword lists, pattern matching, and machine learning classifiers to screen submissions. These systems are trained on large datasets of problematic content, and they learn to flag anything that resembles spam, hate speech, or explicit material. The problem is that emotional writing naturally uses intense language. Words related to death, obsession, longing, and pain frequently appear in genuine unsent letters, and those same words frequently appear in content that moderation systems are designed to block. A heartfelt message about wishing someone were still alive might be flagged because it contains language associated with self-harm content. A message about physical longing might be flagged because it contains language associated with explicit content. The filter does not understand context. It does not know that you are grieving, not threatening. It sees a keyword and makes a decision.

Platform neglect is another factor that cannot be ignored. Many unsent letter platforms were created by individual developers or small teams who were inspired by the concept but did not have the resources or commitment to maintain the platform indefinitely. Over time, the developer's attention shifts elsewhere. Bug reports go unaddressed. The submission pipeline develops issues that no one investigates. The platform continues to accept submissions, because the front end is still functional, but the back end is silently failing. Your submission is accepted by the form but never processed by the system behind it. The developer is not monitoring the logs. No one is watching.

There is also the issue of platform architecture and how submissions are displayed. Some platforms show submissions in reverse chronological order, meaning your post appears at the top briefly and then gets buried under new submissions within hours or minutes. If you did not check the archive immediately after submitting, you might have missed the window when your post was visible. Other platforms use algorithmic or curated display methods that do not show every submission to every visitor. Your post might exist in the database but never surface in the feed that you are scrolling through. The archive is not a simple, complete list. It is a filtered, curated, or algorithmically sorted selection, and your post may not have made the cut.

The emotional impact of this problem goes beyond simple technical frustration. When you submit an unsent letter, you are performing an act of deliberate vulnerability. You are consciously choosing to take something that has been locked inside you and release it into a space where others can encounter it. This act requires courage. It requires trust. It requires a belief that the platform will honor your contribution by preserving it and making it available to readers. When the platform fails to do this, it does not just fail technically. It fails ethically. It breaks a promise that was implicit in the act of accepting your submission.

This is something we care deeply about at Honey, If Only, because we have heard from too many people who had this exact experience on other platforms. People who wrote something real, something that cost them, and had it vanish without a trace. People who tried multiple times and gave up, concluding that their words were not worth holding. People who internalized the platform's technical failure as a personal rejection. That should never happen. No one who summons the courage to write an unsent letter should be made to feel that their words are disposable.

Our approach is built on three commitments that directly address this problem. First, every submission receives a clear confirmation. When you submit a letter to Honey If Only, the platform acknowledges that your words were received. This is not a trivial UI detail. It is a promise. Your submission entered the system. It exists. It will be processed.

Second, every submission is reviewed by a human moderator. Not an algorithm. Not a keyword filter. A person who reads your words, evaluates their sincerity, and makes a judgment about whether they belong in the archive. If your letter is approved, it appears. If it is not approved, it is because a human being made that decision, not because a machine misinterpreted your language. The vast majority of sincere submissions are approved.

Third, the twenty five word constraint dramatically reduces the factors that cause posts to disappear on other platforms. The volume of submissions is more manageable because the word limit naturally deters spam and casual submissions. The moderation queue moves faster because each submission is short enough to evaluate quickly. The storage and display systems are more efficient because the data footprint of each submission is small. Every structural decision that could cause your post to be lost is mitigated by the constraint that also makes the writing better.

The question of why your posts do not show up on The Unsent Project is ultimately a question about what kind of platform deserves your vulnerability. A platform that silently discards your words without explanation does not deserve it. A platform that overwhelms its own infrastructure and loses submissions in the noise does not deserve it. Your unsent letter is not content. It is not a data point. It is a piece of you that you chose to release, and the platform that receives it should treat it accordingly.

Honey If Only exists because we believe that every unsent letter deserves to be held. Twenty five words. Human moderation. A confirmation that your truth was received and preserved. That is the standard. That is what your words are worth.`
  }
];
